// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Je0VSANKTH2Rej9B7SGytrJZukiSvAc',
    appId: '1:865532487361:web:ac2f795e8b5f53f7b3d640',
    messagingSenderId: '865532487361',
    projectId: 'projectm-9d5c9',
    authDomain: 'projectm-9d5c9.firebaseapp.com',
    storageBucket: 'projectm-9d5c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY461f8Q42ubSDg2esBDZh7AghOf4aUPg',
    appId: '1:865532487361:android:e8368715baa4167bb3d640',
    messagingSenderId: '865532487361',
    projectId: 'projectm-9d5c9',
    storageBucket: 'projectm-9d5c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ_Cm5yoLujmBt5PBcF7ZnJKDLwBKY2RI',
    appId: '1:865532487361:ios:108aed7fd019e2a8b3d640',
    messagingSenderId: '865532487361',
    projectId: 'projectm-9d5c9',
    storageBucket: 'projectm-9d5c9.firebasestorage.app',
    iosBundleId: 'com.masterung.projectm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ_Cm5yoLujmBt5PBcF7ZnJKDLwBKY2RI',
    appId: '1:865532487361:ios:108aed7fd019e2a8b3d640',
    messagingSenderId: '865532487361',
    projectId: 'projectm-9d5c9',
    storageBucket: 'projectm-9d5c9.firebasestorage.app',
    iosBundleId: 'com.masterung.projectm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Je0VSANKTH2Rej9B7SGytrJZukiSvAc',
    appId: '1:865532487361:web:fef97d861ae06a86b3d640',
    messagingSenderId: '865532487361',
    projectId: 'projectm-9d5c9',
    authDomain: 'projectm-9d5c9.firebaseapp.com',
    storageBucket: 'projectm-9d5c9.firebasestorage.app',
  );
}
